### ISSUE TITLE
Python 3.5 additions?

### ISSUE THREAD

**Issue by shaolo1** [raff/pygor#2]
Very interesting project so far.  Is it still being worked on?

It would be nice to see unpacking (https://www.python.org/dev/peps/pep-0448/) and f-strings (https://www.python.org/dev/peps/pep-0498/).

**Comment by raff** [comment]
I am using the package "github.com/go-python/gpython" to parse the Python source code, and unfortunately that is based on Python 3.4 and doesn't look it's moving any further.

I don't understand the parser well enough to update it myself so unfortunately for now there is little I can do (actually I was more interested in being able to parse Python 2.x, that "mostly works")

I have not spent much time on this project lately (and It think I have got as far as I can think of pushing it, with Python 3.4) but I am open to suggestion and contributions.

**Comment by shaolo1** [comment]
Thanks for the response and the link to the other repo.  I'll have a look at both projects and see if there's anything I can do.
